stages:
  - deploy

.only-run-prod: &only-run-prod
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/

publish-npm:
  stage: deploy
  image: node:18-alpine
  before_script:
    - npm config set registry https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  script:
    - npm publish --access public
  artifacts:
    paths:
      - dist/
  <<: *only-run-prod
