minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 432000

autoInstallPeers: false
strictPeerDependencies: false
shamefullyHoist: true
shellEmulator: true
packages:
  - '**'
