shellEmulator: true

trustPolicy: no-downgrade

packages:
  - '**'

catalogs:
  deps:
    '@antfu/eslint-config': 6.7.3
    defu: ^6.1.4
    eslint-plugin-case-police: ^2.1.1
    eslint-plugin-file-progress: ^3.0.2
    is-in-ci: ^2.0.0
    local-pkg: ^1.1.2
    resolve-pkg: ^2.0.0
    semver: ^7.7.3
  dev:
    '@aa900031/release-it-config': ^0.1.0
    '@eslint/config-inspector': ^1.4.2
    npm-run-all2: ^8.0.4
    release-it: ^19.2.3
    unbuild: ^3.6.1
  peer:
    eslint: ^9.39.2
  types:
    '@tsconfig/node22': ^22.0.5
    '@types/node': ^22.19.7
    '@types/semver': ^7.7.1
    typescript: ~5.9.3
