name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup
        uses: aa900031/github-actions/setup-node@main
        with:
          no-turbo-cache: 'true'

      - name: Fix lint issue
        run: pnpm run lint --fix

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
        with:
          commit-message: 'chore: apply automated updates'
